name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'

env:
  DOCKER_IMAGE: uwessds/ess412-512-image

jobs:
  build-image-and-push:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Get CalenderVersion UTC Date
      id: calver
      run: echo "::set-output name=version::$(date +'%Y.%m.%d')"

    - name: Build and Push to DockerHub
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: ${{ env.DOCKER_IMAGE }}
        ADDITIONAL_TAG: ${{ steps.calver.outputs.version }}


    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

    - name: Report Image Size and Conda Packages
      if: always()
      run: |
        docker images
        docker run uwhackweek/template:latest conda list --export
